<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Teh Botol Sosro',
                'image' => 'products/teh-botol.jpg',
                'status' => 1,
                'category_id' => 1,
                'code' => strtoupper(Str::random(8)),
                'price' => 5000,
                'stock' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indomie Goreng',
                'image' => 'products/indomie-goreng.jpg',
                'status' => 1,
                'category_id' => 1,
                'code' => strtoupper(Str::random(8)),
                'price' => 3000,
                'stock' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pulpen Standard Hitam',
                'image' => 'products/pulpen.jpg',
                'status' => 1,
                'category_id' => 2,
                'code' => strtoupper(Str::random(8)),
                'price' => 2500,
                'stock' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Tulis Sidu',
                'image' => 'products/buku-sidu.jpg',
                'status' => 1,
                'category_id' => 2,
                'code' => strtoupper(Str::random(8)),
                'price' => 4000,
                'stock' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mouse Logitech M170',
                'image' => 'products/logitech-mouse.jpg',
                'status' => 1,
                'category_id' => 3,
                'code' => strtoupper(Str::random(8)),
                'price' => 150000,
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keyboard Wireless Logitech',
                'image' => 'products/logitech-keyboard.jpg',
                'status' => 1,
                'category_id' => 3,
                'code' => strtoupper(Str::random(8)),
                'price' => 200000,
                'stock' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sabun Lifebuoy 75g',
                'image' => 'products/lifebuoy.jpg',
                'status' => 1,
                'category_id' => 5,
                'code' => strtoupper(Str::random(8)),
                'price' => 3500,
                'stock' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shampoo Pantene 170ml',
                'image' => 'products/pantene.jpg',
                'status' => 1,
                'category_id' => 5,
                'code' => strtoupper(Str::random(8)),
                'price' => 25000,
                'stock' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sapu Ijuk',
                'image' => 'products/sapu.jpg',
                'status' => 1,
                'category_id' => 4,
                'code' => strtoupper(Str::random(8)),
                'price' => 12000,
                'stock' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pembersih Lantai Wipol 800ml',
                'image' => 'products/wipol.jpg',
                'status' => 1,
                'category_id' => 4,
                'code' => strtoupper(Str::random(8)),
                'price' => 18000,
                'stock' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roti Tawar Sari Roti',
                'image' => 'products/roti-tawar.jpg',
                'status' => 1,
                'category_id' => 1,
                'code' => strtoupper(Str::random(8)),
                'price' => 11000,
                'stock' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Air Mineral Aqua 600ml',
                'image' => 'products/aqua.jpg',
                'status' => 1,
                'category_id' => 1,
                'code' => strtoupper(Str::random(8)),
                'price' => 3500,
                'stock' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spidol Snowman Permanent',
                'image' => 'products/snowman.jpg',
                'status' => 1,
                'category_id' => 2,
                'code' => strtoupper(Str::random(8)),
                'price' => 8000,
                'stock' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kabel Charger Micro USB',
                'image' => 'products/kabel-usb.jpg',
                'status' => 1,
                'category_id' => 3,
                'code' => strtoupper(Str::random(8)),
                'price' => 25000,
                'stock' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colokan Listrik 3 Lubang',
                'image' => 'products/colokan.jpg',
                'status' => 1,
                'category_id' => 3,
                'code' => strtoupper(Str::random(8)),
                'price' => 30000,
                'stock' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Detergen Rinso 800gr',
                'image' => 'products/rinso.jpg',
                'status' => 1,
                'category_id' => 4,
                'code' => strtoupper(Str::random(8)),
                'price' => 19000,
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pasta Gigi Pepsodent',
                'image' => 'products/pepsodent.jpg',
                'status' => 1,
                'category_id' => 5,
                'code' => strtoupper(Str::random(8)),
                'price' => 8000,
                'stock' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minyak Goreng Bimoli 1L',
                'image' => 'products/bimoli.jpg',
                'status' => 1,
                'category_id' => 1,
                'code' => strtoupper(Str::random(8)),
                'price' => 17000,
                'stock' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kertas HVS A4 80gsm',
                'image' => 'products/hvs.jpg',
                'status' => 1,
                'category_id' => 2,
                'code' => strtoupper(Str::random(8)),
                'price' => 45000,
                'stock' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hand Sanitizer 100ml',
                'image' => 'products/sanitizer.jpg',
                'status' => 1,
                'category_id' => 5,
                'code' => strtoupper(Str::random(8)),
                'price' => 10000,
                'stock' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
